name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full clone to allow getting the last tag
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          gradle-version: 8.1.1
      - name: Setup Vars
        id: vars
        run: |
          echo "LAST_TAG=$(git describe --abbrev=0 HEAD^ --tags)" >> "$GITHUB_OUTPUT"
          echo "CURRENT_VERSION=$(gradle -q printVersion)" >> "$GITHUB_OUTPUT"

      - name: Setup release info
        id: releaseInfo
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.ref_name }}

      - name: Version Check
        if: ${{ steps.vars.outputs.CURRENT_VERSION != github.ref_name }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed("Bot configured with incorrect version\Bot Version: ${{steps.vars.outputs.CURRENT_VERSION}}\nGithub Version: ${{github.ref_name}}")

      - name: deploy
        run: |
          gradle build
        shell: bash
      - name: Upload jar to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/libs/secret-santa-bot-*-all.jar